<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="attachment_products" id="in_attachment_products" data-form-part="productattachment_attachgrid_editing" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "ITM_MagB1/productfiles/assign-products": {
                "selectedProducts": <?= /* @noEscape */ $block->getProductsJson() ?>,
                "gridJsObjectName": <?= /* @noEscape */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
