<?php
/**
 * Copyright © Wagento, Inc. All rights reserved.
 */
/** @var \Wagento\Sales\Block\Order\History\CancelledOrders $block */
?>
<?php $orders = $block->getOrdersCancelled(); ?>

<?php if ($orders && count($orders)) : ?>
    <data class="content-data">
        <?php /** @var \Magento\Sales\Model\Order $order */?>
        <?php foreach ($orders as $order) : ?>
            <div class="row">
                <div class="order_data">
                    <div class="date">
                        <span><?=__('Placed Order');?></span>
                        <span><?=$block->formatDate($order->getCreatedAt());?></span>
                    </div>
                    <div class="total">
                        <span><?=__('Total');?></span>
                        <span><?= /* @noEscape */ $order->formatPrice($order->getGrandTotal()) ?></span>
                    </div>
                    <div class="number-actions">
                        <span><?=__('Order #');?><?=$block->escapeHtml($order->getRealOrderId());?></span>
                        <div class="actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('Order Details')) ?></span>
                            </a>

                            <?php if ($order->hasInvoices()):?>
                                <a href="<?= $block->escapeUrl($block->getInvoiceUrl($order)) ?>" class="action view">
                                    <span> | <?= $block->escapeHtml(__('Invoice')) ?></span>
                                </a>
                            <?php endif ?>

                            <?php if ($order->hasCreditmemos()):?>
                                <a href="<?= $block->escapeUrl($block->getCreditMemoUrl($order)) ?>" class="action view">
                                    <span> | <?= $block->escapeHtml(__('Creditmemo')) ?></span>
                                </a>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </data>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
