<?php
/**
 * Copyright © Wagento, Inc. All rights reserved.
 */
/** @var \Wagento\Sales\Block\Order\History\Orders $block */
?>
<div class="filters">
    <span class="qty">
        <span class="number">
            <?/*=$block->getOrders()->getSize() . ' ' . __('Orders');*/?>
        </span>
        <?=__('placed on');?>:
    </span>
    <select name="year" id="year">
        <option value="30 days"><?=__('Last %1 Days', ['30']);?></option>
        <option value="3 months"><?=__('%1 Months ago', ['3']);?></option>
        <option value="<?=date('Y');?>"><?=date('Y');?></option>
        <?php
        $initial = date('Y', strtotime('-1 year'));
        $end = date('Y', strtotime('-4 years'));
        for ($i = $initial; $i >= $end; $i--) {
            echo "<option value='$i'>$i</option>";
        }
        ?>
    </select>
</div>
<data class="content-data" id="content-data-order">
    <?php /** @var \Magento\Sales\Model\Order $order */?>
    <?= $block->getChildBlock('sales.order.history.orders.items')->toHtml();?>
</data>
