<?php
/**
 * Copyright © Wagento, Inc. All rights reserved.
 */
/** @var \Wagento\Sales\Block\Order\History $block */

use Wagento\Sales\Block\Order\History;

?>
<?= $block->getChildHtml('info') ?>

<div class="table-wrapper orders-history"
     data-mage-init='{
        "Wagento_Sales/js/filter": {
            "elementYear": "#year",
            "elementSearchText": "#search_text",
            "elementSearch": "#search-history-orders",
            "containerPager": "#container-pager",
            "inputHiddenPageNumber": "#p",
            "buttonPage": "#load-more",
            "containerFilter": "#filter",
            "tabs": [
                {
                    "default": "true",
                    "urlAjax": "<?=$block->getUrl('sales/history_page/orders');?>",
                    "elementAddHtml": "#content-data-order",
                    "elementTabWihtData": "#orders",
                    "elementTab": "#tab-order"
                },
                {
                    "urlAjax": "<?=$block->getUrl('sales/history_page/reorder');?>",
                    "elementAddHtml": "#content-data-reorder",
                    "elementTabWihtData": "#reorder",
                    "elementTab": "#tab-reorder"
                },
                {
                    "urlAjax": "<?=$block->getUrl('sales/history_page/cancelled');?>",
                    "elementAddHtml": "#content-data-cancelled",
                    "elementTabWihtData": "#cancelled_orders",
                    "elementTab": "#tab-cancelled"
                }
            ]
        }
     }'>
    <div class="tabs">
        <span id="tab-order" class="<?=$block->isOrder() ? 'active' : '';?>">
            <a>
                <?=__('Orders');?>
            </a>
            <?php if ($block->isOrder()) :?>
                <i class="fa-solid fa-minus"></i>
            <?php else:?>
                <i class="fa-solid fa-plus"></i>
            <?php endif;?>
        </span>
        <span id="tab-reorder" class="<?=$block->isReorderProducts() ? 'active' : '';?>">
            <a>
                <?=__('Order again');?>
            </a>
            <?php if ($block->isReorderProducts()) :?>
                <i class="fa-solid fa-minus"></i>
            <?php else:?>
                <i class="fa-solid fa-plus"></i>
            <?php endif;?>
        </span>
        <span id="tab-cancelled" class="<?=$block->isCancelledOrder() ? 'active' : '';?>">
            <a>
                <?=__('Cancelled Orders');?>
            </a>
            <?php if ($block->isCancelledOrder()) :?>
                <i class="fa-solid fa-minus"></i>
            <?php else:?>
                <i class="fa-solid fa-plus"></i>
            <?php endif;?>
        </span>
    </div>

    <div class="orders inactive" id="orders">
        <?= $block->getChildHtml('sales.order.history.orders') ?>
    </div>

    <div class="reorder inactive" id="reorder">
        <?= $block->getChildHtml('sales.order.history.reorders.products') ?>
    </div>

    <div class="cancelled_orders inactive" id="cancelled_orders">
        <?= $block->getChildHtml('sales.order.history.cancelled.orders') ?>
    </div>

    <div class="pager-see-more" id="container-pager">
        <hr/>
        <div id="pagination-order">
            <button type="button" class="load-more" id="load-more">
                <span><?=__('See More');?></span>
            </button>
            <input type="hidden" id="p" name="p" />
        </div>
        <hr/>
    </div>
</div>
