<?php
/** @var \Magento\Customer\Block\Account\AuthenticationPopup $block */
?>
<form id="login-form-popup" class="login-form" onsubmit="login"
      method="post" data-bind="scope:'authenticationAjax'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</form>
<script type="text/x-magento-init">
    {
        "#login-form-popup": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "authenticationAjax": {
                        "component": "Magento_Customer/js/authentication-ajax",
                        "form": "#login-form-popup",
                        "elementClick": "[id^=do-login]",
                        "config": <?=$block->getSerializedConfig()?>
                    }
                }
            }
        }
    }
</script>
