stage:
  global:
    SCD_THREADS: 4
    SKIP_HTML_MINIFICATION: true
  build:
    SKIP_SCD: false
    SCD_STRATEGY: compact
    VERBOSE_COMMANDS: "-vv"
    QUALITY_PATCHES:
      - "ACSD-48807"
      - "ACSD-48857"
      - "ACSD-49065"
      - "ACSD-49286"
      - "ACSD-48362"
      - "MDVA-15546"
      - "MDVA-30106"
      - "MDVA-12304"
      - "MDVA-19640"
      - "ACSD-48417"
      - "ACSD-48216"
      - "ACSD-47908"
      - "ACSD-49370"
      - "ACSD-49574"
  deploy:
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\Redis'
    REDIS_USE_SLAVE_CONNECTION: true
    MYSQL_USE_SLAVE_CONNECTION: true
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 2000
      consumers:
        - media.gallery.synchronization
        - media.content.synchronization
        - media.gallery.renditions.update
        - exportProcessor
        - matchCustomerSegmentProcessor
        - product_action_attribute.update
        - product_action_attribute.website.update
        - inventory.source.items.cleanup
        - inventory.mass.update
        - inventory.reservations.cleanup
        - inventory.reservations.update
        - inventory.reservations.updateSalabilityStatus
        - inventory.indexer.sourceItem
        - inventory.indexer.stock
