stage:
  global:
    SCD_THREADS: 4
    SKIP_HTML_MINIFICATION: true
  build:
    SKIP_SCD: false
    SCD_STRATEGY: compact
    VERBOSE_COMMANDS: "-vv"
    QUALITY_PATCHES:
      - MDVA-12304
      - MDVA-19640
      - MDVA-44940
      - ACSD-47027
      - ACSD-43887
      - ACSD-47280
      - ACSD-47106
      - ACSD-45168
      - ACSD-47137
      - ACSD-48234
  deploy:
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\Redis'
    REDIS_USE_SLAVE_CONNECTION: true
    MYSQL_USE_SLAVE_CONNECTION: true
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 2000
      consumers:
        - media.gallery.synchronization
        - media.content.synchronization
        - media.gallery.renditions.update
        - exportProcessor
        - matchCustomerSegmentProcessor
        - product_action_attribute.update
        - product_action_attribute.website.update
        - inventory.source.items.cleanup
        - inventory.mass.update
        - inventory.reservations.cleanup
        - inventory.reservations.update
        - inventory.reservations.updateSalabilityStatus
        - inventory.indexer.sourceItem
        - inventory.indexer.stock
