<?php
/**
 * Rutavity checkout success page customization
 * @package Milan_Rutavity
 * @author Rudie Wang <rudi.wang@wagento.com>
 */

?>
<?php /** @var $block \Wagento\ModifiedCheckout\Block\PurchaseOrder\Success */ ?>
<div class="checkout-success">
    <h1 class="checkout-success-title"><?= $block->escapeHtml(__('Thank you for your purchase!')) ?></h1>
    <?php if ($block->getPurchaseOrderId()) :?>
        <?php $incrementId = $escaper->escapeHtml($block->getPurchaseOrder()->getIncrementId());?>
        <?php if ($block->getCanViewOrder()) :?>
            <p class="order-number"><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $incrementId)), ['a', 'strong']) ?></p>
        <?php  else :?>
            <p class="order-number"><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $incrementId), ['span']) ?></p>
        <?php endif;?>
        <p class="order-date"><?= $block->escapeHtml(__('Created on <span>%1</span>', $block->getOrderDate()), ['span']) ?></p>

        <div class="order-details">
            <div class="information billing-information">
                <p class="information-title"><?= $block->escapeHtml(__('Billing Information')) ?></p>
                <div class="information-content">
                    <span class="information-name"><?=$block->getPurchaseOrder()->getSnapshotQuote()->getBillingAddress()->getName() ?? '';?></span>
                    <span class="information-street"><?=$block->getPurchaseOrder()->getSnapshotQuote()->getBillingAddress()->getStreetFull() ?? '';?></span>
                    <span class="information-street"><?=$block->getPurchaseOrder()->getSnapshotQuote()->getBillingAddress()->getCity() ?? '';?></span>
                    <span class="information-phone"><?=$block->getPurchaseOrder()->getSnapshotQuote()->getBillingAddress()->getTelephone() ?? '';?></span>
                </div>
            </div>

            <div class="information shipping-information">
                <p class="information-title"><?= $block->escapeHtml(__('Shipping Information')) ?></p>
                <div class="information-content">
                    <span class="information-name"><?=$block->getPurchaseOrder()->getSnapshotQuote()->getShippingAddress()->getName() ?? '';?></span>
                    <span class="information-street"><?=$block->getPurchaseOrder()->getSnapshotQuote()->getShippingAddress()->getStreetFull() ?? '';?></span>
                    <span class="information-street"><?=$block->getPurchaseOrder()->getSnapshotQuote()->getShippingAddress()->getCity() ?? '';?></span>
                    <span class="information-phone"><?=$block->getPurchaseOrder()->getSnapshotQuote()->getShippingAddress()->getTelephone() ?? '';?></span>
                </div>
            </div>

            <div class="information payment-information">
                <p class="information-title"><?= $block->escapeHtml(__('Payment Information')) ?></p>
                <div class="information-content">
                    <span class="information-payment"><?=__($block->getPurchaseOrder()->getSnapshotQuote()->getPayment()->getMethodInstance()->getTitle()) ?? '';?></span>
                    <span class="information-additional"><?=implode('<br>', $block->getPurchaseOrder()->getSnapshotQuote()->getPayment()->getAdditionalData() ?? []);?></span>
                </div>
            </div>
        </div>
    <?php endif;?>
</div>

<?= $block->getAdditionalInfoHtml() ?>
