<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\PurchaseOrder\Block\PurchaseOrder\View $block
 * @var \Magento\Framework\Escaper $escaper
 */

$htmlClass = 'product data items purchase-order-data-items';

if ($block->getNameInLayout() !== 'purchase.order.index.view') {
    $htmlClass .= ' quote-details-items';
}
?>

<form method="GET">
    <div class="table-wrapper title-filter">
        <div class="title-my-orders">
            <span><b><?=__('Purchase Orders');?></b></span>
            <div class="filter" id="filter">
                <div class="text-search">
                    <i class="fa-solid fa-magnifying-glass"></i>
                    <input type="text"
                           id="search_text"
                           name="search_text"
                           placeholder="<?=__('Search all orders');?>"
                           value="<?=$block->getRequest()->getParam('search_text');?>"
                    >
                </div>
                <button type="submit" id="search-history-orders">
                    <span><?=__('Search Orders');?></span>
                </button>
            </div>
        </div>
    </div>
</form>

<div class="<?= $escaper->escapeHtmlAttr($htmlClass) ?>"
     data-mage-init='{"negotiableQuoteTabs":{"openedState":"active", "saveState":true}, "Magento_PurchaseOrder/js/animation-tabs":{}}'
     id="details-items-tabs-data"
     style="display: none;"
    >
    <?php $layout = $block->getLayout();
    foreach ($block->getSortedChildNames() as $name):
        $html = $layout->renderElement($name);
        if (!trim($html)) {
            continue;
        }
        $childBlock = $layout->getBlock($name);
        $alias = $layout->getElementAlias($name);

        $label = $block->getChildData($alias, 'title');
        $cssClasses = $block->getChildData($alias, 'css_class') ?? '';

        ?>
        <div class="data item title <?= $escaper->escapeHtmlAttr($alias); ?>"
             aria-labeledby="tab-label-items-<?= $escaper->escapeHtmlAttr($alias); ?>"
             data-role="collapsible" id="tab-label-<?= $escaper->escapeHtmlAttr($alias); ?>">
            <a class="data switch"
               tabindex="-1"
               data-toggle="switch"
               href="#<?= $escaper->escapeHtmlAttr($alias); ?>"
               id="tab-label-items-<?= $escaper->escapeHtmlAttr($alias); ?>">
                <?= $childBlock->getChildHtml('tab.link.label.before'); ?>
                <?= $escaper->escapeHtml($label); ?>
                <?= $childBlock->getChildHtml('tab.link.label.after'); ?>
            </a>
        </div>

        <div class="data item content <?= $escaper->escapeHtmlAttr($cssClasses); ?>"
             id="<?= $escaper->escapeHtmlAttr($alias); ?>" data-role="content">
            <?= /* @noEscape */ $html ?>
        </div>
    <?php endforeach; ?>
</div>
