<?php
/**
 * Rutavity review wrapper template
 * @package Milan_Rutavity
 * @author Rudie Wang <rudi.wang@wagento.com>
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<?= $block->getChildHtml() ?>
<div id="product-review-container" data-role="product-review"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
