<?php
/**
 * Rutavity header top bar mini-logo template
 * @package Milan_Rutavity
 */

/**
 * @var \Wagento\Catalog\Block\MiniLogos $block
 * @var \Magento\Framework\Escaper $escaper
 */

use Magento\Framework\App\Filesystem\DirectoryList;

$path = $block->getLogoFile();
$label = $block->getLogoAlt();
?>
<?php foreach ($block->getConfigBrands() as $id => $page):?>
    <a class="mini-logos" href="<?=$block->getUrl('catalog/category/view/category/' . $id);?>">
        <img src="<?= $block->escapeHtml($block->getUrl(DirectoryList::MEDIA . '/customPagesBrands/brands/').$page['image_brand']) ?>" alt="<?= $block->escapeHtml($page['title']) ?>" />
    </a>
<?php endforeach;?>
