<?php
/**
 * Rutavity header top bar mini-logo template
 * @package Milan_Rutavity
 */

/**
 * @var \Wagento\Catalog\Block\MiniLogos $block
 * @var \Magento\Framework\Escaper $escaper
 */

$path = $block->getLogoFile();
$label = $block->getLogoAlt();
?>
<?php foreach ($block->getConfigBrands() as $id => $page):?>
    <a class="mini-logos" href="<?=$block->getUrl('catalog/category/view/category/' . $id);?>">
        <img src="<?= $block->escapeHtml($block->getConfigUrlBrandsImages($page['image_brand']));?>"
             alt="<?= $block->escapeHtml($page['title']) ?>"
        />
    </a>
<?php endforeach;?>
