
<?php $_order = $block->getOrder() ?>
<?php $_magb_helper = $this->helper('ITM\MagB1\Helper\Data'); ?>
<?php $customer_id = $_order->getCustomerId();?>
<?php $type ="sales_shipment"; ?>
<?php
$allFiles = [];
foreach ($_order->getShipmentsCollection() as $_shipment):
    $increment_id = $_shipment->getIncrementId();
    $files = $_magb_helper->getShipmentFiles($customer_id, $increment_id);
    if(count($files)) {
        $allFiles = array_merge($allFiles, $files);
    }
endforeach;
?>
<?php if(count($allFiles) == 0) return ; ?>

<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?php  echo __('Shipments Files') ?></strong>
    </div>
    <div class="block-content">
   <ul style=" list-style-type: none;">
	   	<?php foreach ($allFiles as $file): ?>
   		 <?php
   		 $file_info = pathinfo ($file["path"]);
   		 $ext = "";
   		 if(isset($file_info['extension'])) {
   		     $ext =  $file_info['extension'];
   		 }
   		 ?>
   		 <li style="float: left ;  margin:10px;text-align:center">
   		 <a target="_blank" href="<?php echo $this->getUrl('magb1/download/index',["type"=>$type,"id" =>$file["entity_id"]]); ?>">
   		 <img width=40 src="<?php echo $block->getViewFileUrl('ITM_MagB1::images/'.$ext.'.png'); ?>" title="<?php echo $file["path"]?> " alt="<?php echo $file["path"]?> " />
   		 <?php //echo $file["path"]?>
   		 </a>

   		<?php if(!empty($file["description"])):?>

   			<div>
                <a target="_blank" href="<?php echo $this->getUrl('magb1/download/index',["type"=>$type,"id" =>$file["entity_id"]]); ?>">
                    <span>
                        <?php echo $file["description"];?>
                    </span>
                </a>
            </div>

   		<?php endif;?>
   		</li>

   		<?php endforeach; ?>
   	</ul>
    </div>
</div>    




