<?php
/**
 * Copyright © Wagento, Inc. All rights reserved.
 */
/** @var \Wagento\Sales\Block\Order\History\ReorderProducts $block */
/** @var \Magento\Framework\Escaper $escaper */
use Magento\Framework\App\Action\Action;
?>
<?php $ordersItems = $block->getOrdersItems(); ?>
<?php /** @var \Magento\Sales\Model\Order\Item $ordersItem */ ?>
<?php foreach ($ordersItems as $ordersItem):?>
    <?php $product = $ordersItem->getProduct();?>
    <?php if(!$ordersItem->getProduct()) {continue;} ?>
    <?php if ($ordersItem->getHasChildren()) {continue;}?>
    <div class="product">
        <div class="image">
            <?=$block->getImage($product, 'cart_page_product_thumbnail')->toHtml();?>
        </div>
        <div class="data">
            <span class="name"><?=$ordersItem->getName();?></span>
            <span class="price"><?=$block->getProductPrice($product);?></span>
        </div>
        <div class="reorder">
            <?php $postParams = $block->getAddToCartPostParams($product); ?>
            <form data-role="tocart-form"
                  id="form-<?= $escaper->escapeHtml($product->getSku()) ?>"
                  data-product-sku="<?= $escaper->escapeHtml($product->getSku()) ?>"
                  action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                  method="post">
                <?= $block->getBlockHtml('formkey') ?>
                <input type="hidden"
                       name="product"
                       value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                <input type="hidden"
                       name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                       value="<?=
                       /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                       ?>">
                <input type="hidden" value="<?php echo $block->getFormKey(); ?>" name="form_key" />
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Add')) ?>"
                        class="action tocart primary"
                        disabled>
                    <span><?= $escaper->escapeHtml(__('Add')) ?></span>
                    <img src="<?=$block->getViewFileUrl('images/assets/cart-green.svg');?>">
            </form>
        </div>
    </div>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form]": {
            "Magento_Catalog/js/catalog-add-to-cart": {
                "product_sku": "<?= $escaper->escapeJs($ordersItem->getProduct()->getSku()) ?>",
                "addToCartButtonTextDefault": "<?= $escaper->escapeHtml(__('Add')) ?>"
            }
        }
    }
    </script>
<?php endforeach;?>
