<?php
/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */
$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
    <tr class="item-actions">
        <td colspan="5">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </td>
    </tr>
    <tr class="item-info">
        <td colspan="5">
            <div data-th="<?=$block->escapeHtml(__('Item')) ?>" class="col item">
                <div>
                    <?=$block->getParentBlock()
                        ->getChildBlock('checkout.products.list.wagento.promotion.season')
                        ->setProduct($_item->getProduct())
                        ->toHtml();?>
                    <?php if ($block->hasProductUrl()): ?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                           title="<?= $block->escapeHtml($block->getProductName()) ?>"
                           tabindex="-1"
                           class="product-item-photo">
                    <?php else: ?>
                        <span class="product-item-photo">
                    <?php endif; ?>
                    <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                    <?php if ($block->hasProductUrl()): ?>
                        </a>
                    <?php else: ?>
                        </span>
                    <?php endif; ?>
                </div>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <?php if ($block->hasProductUrl()): ?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                        <?php else: ?>
                            <?= $block->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </strong>
                    <?php if ($_options = $block->getOptionList()): ?>
                        <dl class="item-options">
                            <?php foreach ($_options as $_option): ?>
                                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                <dd>
                                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                        <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a']) ?>
                                    <?php else: ?>
                                        <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                    <?php endif; ?>
                                </dd>
                            <?php endforeach; ?>
                        </dl>
                    <?php endif; ?>
                    <?php if ($messages = $block->getMessages()): ?>
                        <?php foreach ($messages as $message): ?>
                            <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                                <div><?= $block->escapeHtml($message['text']) ?></div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock): ?>
                        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif; ?>
                </div>
            </div>

            <?php if ($canApplyMsrp): ?>
                <div class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                    <span class="pricing msrp">
                        <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                        <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                        <a href="#" class="action help map"
                           id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                           data-mage-init='{"addToCart":{
                                                "origin": "info",
                                                "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                                "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                                "showAddToCart": false
                                                }
                                            }'
                        >
                            <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                        </a>
                    </span>
                </div>
            <?php else: ?>
                <div class="col price" data-th="<?=__('P/Unity');?>: ">
                    <?= $block->getUnitPriceHtml($_item) ?>
                </div>
            <?php endif; ?>
            <div class="col qty">
                <div class="field qty">
                    <div class="control qty">
                        <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                               data-mage-init='{"changeQty": {"addQty":"#add-qty-<?= $block->escapeHtmlAttr($_item->getId()) ?>",
                               "delQty":"#del-qty-<?= $block->escapeHtmlAttr($_item->getId()) ?>",
                               "qty":"#cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty",
                               "form":"#form-validate"}}'>
                            <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                            <input type="button" class="del-qty" id="del-qty-<?= $block->escapeHtmlAttr($_item->getId()) ?>" value="-" />
                            <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                   name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                   data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                   value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                   type="number"
                                   size="4"
                                   step="any"
                                   title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                   class="input-text qty"
                                   data-validate="{required:true,'validate-greater-than-zero':true}"
                                   data-item-qty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                   data-role="cart-item-qty"/>
                            <input type="button" class="add-qty" id="add-qty-<?= $block->escapeHtmlAttr($_item->getId()) ?>" value="+" />
                        </label>
                    </div>
                </div>
            </div>

            <div class="col subtotal" data-th="<?= $block->escapeHtml(__('Total'));?>: ">
                <?php if ($canApplyMsrp): ?>
                    <span class="cart msrp subtotal">--</span>
                <?php else: ?>
                    <?= $block->getRowTotalHtml($_item) ?>
                <?php endif; ?>
            </div>
        </td>
    </tr>
    <?=$block->getParentBlock()
        ->getChildBlock('cart.promotion.season')
        ->setItem($_item)
        ->toHtml();?>
</tbody>
