<style>
    #html-body [data-pb-style=DO3VE8O],
    #html-body [data-pb-style=REJDGTN],
    #html-body [data-pb-style=T0P7E1D],
    #html-body [data-pb-style=T8IO2GC],
    #html-body [data-pb-style=TIH51I5],
    #html-body [data-pb-style=XEY2FHJ] {
        border-width: 1px
    }

    #html-body [data-pb-style=CHTQSB1] {
        text-align: center
    }

    #html-body [data-pb-style=VRP6GVW] {
        border-width: 1px;
        min-height: 300px
    }

    #html-body [data-pb-style=FHEVQ9P], #html-body [data-pb-style=KIYPT3C] {
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll
    }

    #html-body [data-pb-style=FHEVQ9P] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column
    }

    #html-body [data-pb-style=KIYPT3C] {
        text-align: center;
        align-self: stretch
    }

    #html-body [data-pb-style=CGSWTM6] {
        display: flex;
        width: 100%
    }

    #html-body [data-pb-style=TYH99RM] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        width: 50%;
        align-self: stretch
    }

    #html-body [data-pb-style=WO8QUR7] {
        text-align: center;
        margin: 10px 10px 10px 15px;
        border-style: none
    }

    #html-body [data-pb-style=A1IVKEA], #html-body [data-pb-style=WL917L3] {
        max-width: 100%;
        height: auto
    }

    #html-body [data-pb-style=X6X8P03] {
        justify-content: center;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        width: calc(50% - 20px);
        margin-left: 10px;
        margin-right: 10px;
        align-self: stretch
    }

    #html-body [data-pb-style=F4Q0BIE] {
        margin-left: 15px;
        margin-right: 15px
    }

    #html-body [data-pb-style=OJLLULW] {
        width: 100%;
        border-width: 1px;
        border-color: #cecece;
        display: inline-block
    }

    #html-body [data-pb-style=L33T0U4] {
        text-align: center;
        margin-left: 10px;
        margin-right: 10px
    }

    #html-body [data-pb-style=T81C5D2] {
        max-width: 1000px
    }

    #html-body [data-pb-style=IBXJLHP] {
        width: 100%;
        border-width: 1px;
        border-color: #cecece;
        display: inline-block
    }

    #html-body [data-pb-style=AP3X06Y] {
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        align-self: stretch
    }

    #html-body [data-pb-style=JLXF9GK] {
        display: flex;
        width: 100%
    }

    #html-body [data-pb-style=ONT9N6R] {
        justify-content: center;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        width: 100%;
        margin-left: 10px;
        margin-right: 10px;
        align-self: center
    }

    #html-body [data-pb-style=R7XW7DD] {
        margin: 10px 15px
    }

    #html-body [data-pb-style=QXMXQ45] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll
    }

    #html-body [data-pb-style=X6VXB0I] {
        margin-left: 15px;
        margin-right: 15px
    }

    #html-body [data-pb-style=ER6X3EN], #html-body [data-pb-style=N2WQJIC] {
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll
    }

    #html-body [data-pb-style=N2WQJIC] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column
    }

    #html-body [data-pb-style=ER6X3EN] {
        align-self: stretch
    }

    #html-body [data-pb-style=HS8R1IU] {
        display: flex;
        width: 100%
    }

    #html-body [data-pb-style=PVAI2HJ] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        width: calc(50% - 20px);
        margin: 10px;
        align-self: stretch
    }

    #html-body [data-pb-style=BA6HLUF] {
        margin-left: 10px;
        margin-right: 10px
    }

    #html-body [data-pb-style=WSOXO02] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        width: 50%;
        align-self: stretch
    }

    #html-body [data-pb-style=INV3X4E] {
        text-align: center;
        margin-left: 10px;
        margin-right: 10px;
        border-style: none
    }

    #html-body [data-pb-style=RM0OS9O], #html-body [data-pb-style=WSB8P4T] {
        max-width: 100%;
        height: auto
    }

    #html-body [data-pb-style=GULP6O5], #html-body [data-pb-style=WLT33Y4] {
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll
    }

    #html-body [data-pb-style=GULP6O5] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column
    }

    #html-body [data-pb-style=WLT33Y4] {
        align-self: stretch
    }

    #html-body [data-pb-style=B3QEBME] {
        display: flex;
        width: 100%
    }

    #html-body [data-pb-style=GOHNECL], #html-body [data-pb-style=VK3YGGS] {
        justify-content: center;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        align-self: stretch
    }

    #html-body [data-pb-style=VK3YGGS] {
        width: calc(50% - 20px);
        margin-left: 10px;
        margin-right: 10px
    }

    #html-body [data-pb-style=GOHNECL] {
        text-align: center;
        width: 50%;
        margin-top: 10px
    }

    #html-body [data-pb-style=PCRT4IQ] {
        border-style: none
    }

    #html-body [data-pb-style=N9VID07], #html-body [data-pb-style=NK5LJDS] {
        max-width: 100%;
        height: auto
    }

    #html-body [data-pb-style=C55NTUS] {
        display: flex;
        width: 100%
    }

    #html-body [data-pb-style=OMDHBBM] {
        justify-content: center;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        text-align: center;
        width: 50%;
        align-self: stretch
    }

    #html-body [data-pb-style=UOR7JI1] {
        border-style: none
    }

    #html-body [data-pb-style=JN4N1US], #html-body [data-pb-style=NE03FKD] {
        max-width: 100%;
        height: auto
    }

    #html-body [data-pb-style=QGE098C] {
        justify-content: center;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        width: calc(50% - 20px);
        margin-left: 10px;
        margin-right: 10px;
        align-self: stretch
    }

    #html-body [data-pb-style=K4CAPRK] {
        display: flex;
        width: 100%
    }

    #html-body [data-pb-style=LPNAY8B] {
        justify-content: center;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        text-align: center;
        width: 50%;
        align-self: stretch
    }

    #html-body [data-pb-style=LB22LBT] {
        margin-left: 10px;
        margin-right: 10px
    }

    #html-body [data-pb-style=V3SC9AA] {
        justify-content: center;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        text-align: center;
        width: calc(50% - 15px);
        margin-left: 15px;
        align-self: stretch
    }

    #html-body [data-pb-style=KRXUTYJ] {
        text-align: center;
        margin-left: 15px;
        border-style: none
    }

    #html-body [data-pb-style=IV2SJ6L], #html-body [data-pb-style=KX5R3MI] {
        max-width: 100%;
        height: auto
    }

    #html-body [data-pb-style=KNXPWY5] {
        display: flex;
        width: 100%
    }

    #html-body [data-pb-style=TTTXLJ5] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        width: 50%;
        align-self: stretch
    }

    #html-body [data-pb-style=XJI0UVI] {
        text-align: center;
        margin-top: 15px;
        border-style: none
    }

    #html-body [data-pb-style=IQ61NPS], #html-body [data-pb-style=NW69DC4] {
        max-width: 100%;
        height: auto
    }

    #html-body [data-pb-style=VQGL9C1] {
        justify-content: center;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll;
        width: 50%;
        align-self: stretch
    }

    #html-body [data-pb-style=S6YPJJJ] {
        text-align: center;
        margin-left: 10px;
        margin-right: 10px
    }

    #html-body [data-pb-style=DVWU7QI] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll
    }

    #html-body [data-pb-style=YPTGKLL] {
        text-align: center;
        margin: 10px;
        border-style: none
    }

    #html-body [data-pb-style=DWHSGDW], #html-body [data-pb-style=TAAIMMI] {
        max-width: 100%;
        height: auto
    }

    #html-body [data-pb-style=G4JPTI2] {
        text-align: center;
        margin: 10px;
        border-style: none
    }

    #html-body [data-pb-style=FW2HFS0], #html-body [data-pb-style=YVFKH41] {
        max-width: 100%;
        height: auto
    }

    #html-body [data-pb-style=YQ817RO] {
        text-align: center;
        margin-top: 10px;
        margin-bottom: 10px;
        border-style: none
    }

    #html-body [data-pb-style=QBPTBQN], #html-body [data-pb-style=V3IWSCQ] {
        max-width: 100%;
        height: auto
    }

    #html-body [data-pb-style=R0N8R2A] {
        justify-content: flex-start;
        display: flex;
        flex-direction: column;
        background-position: left top;
        background-size: cover;
        background-repeat: no-repeat;
        background-attachment: scroll
    }

    #html-body [data-pb-style=MMV54CO] {
        text-align: center;
        margin: 15px
    }

    @media only screen and (max-width: 768px) {
        #html-body [data-pb-style=G4JPTI2], #html-body [data-pb-style=INV3X4E], #html-body [data-pb-style=KRXUTYJ], #html-body [data-pb-style=PCRT4IQ], #html-body [data-pb-style=UOR7JI1], #html-body [data-pb-style=WO8QUR7], #html-body [data-pb-style=XJI0UVI], #html-body [data-pb-style=YPTGKLL], #html-body [data-pb-style=YQ817RO] {
            border-style: none
        }
    }</style>
<div class="tab-align-center" data-content-type="tabs" data-appearance="default" data-active-tab="0"
     data-element="main">
    <ul role="tablist" class="tabs-navigation" data-element="navigation" data-pb-style="CHTQSB1">
        <li role="tab" class="tab-header" data-element="headers" data-pb-style="XEY2FHJ"><a href="#Y0EHBR0"
                                                                                            class="tab-title"><span
                    class="tab-title">General</span></a></li>
        <li role="tab" class="tab-header" data-element="headers" data-pb-style="T8IO2GC"><a href="#V4UDEJV"
                                                                                            class="tab-title"><span
                    class="tab-title">Características</span></a></li>
        <li role="tab" class="tab-header" data-element="headers" data-pb-style="REJDGTN"><a href="#N0LTS12"
                                                                                            class="tab-title"><span
                    class="tab-title">Geometría</span></a></li>
        <li role="tab" class="tab-header" data-element="headers" data-pb-style="TIH51I5"><a href="#LBBTNDB"
                                                                                            class="tab-title"><span
                    class="tab-title">Tecnología</span></a></li>
        <li role="tab" class="tab-header" data-element="headers" data-pb-style="T0P7E1D"><a href="#GYI8697"
                                                                                            class="tab-title"><span
                    class="tab-title">Beneficios</span></a></li>
        <li role="tab" class="tab-header" data-element="headers" data-pb-style="DO3VE8O"><a href="#NRDV67W"
                                                                                            class="tab-title"><span
                    class="tab-title">Documentos</span></a></li>
    </ul>
    <div class="tabs-content" data-element="content" data-pb-style="VRP6GVW">
        <div data-content-type="tab-item" data-appearance="default" data-tab-name="General" data-background-images="{}"
             data-element="main" id="Y0EHBR0" data-pb-style="FHEVQ9P">
            <div class="pagebuilder-column-group" data-background-images="{}" data-content-type="column-group"
                 data-appearance="default" data-grid-size="12" data-element="main" data-pb-style="KIYPT3C">
                <div class="pagebuilder-column-line" data-content-type="column-line" data-element="main"
                     data-pb-style="CGSWTM6">
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="TYH99RM">
                        <figure data-content-type="image" data-appearance="full-width" data-element="main"
                                data-pb-style="WO8QUR7"><img class="pagebuilder-mobile-hidden"
                                                             src="{{media url=wysiwyg/Mi_proyecto_1.jpg}}" alt=""
                                                             title="" data-element="desktop_image"
                                                             data-pb-style="A1IVKEA"><img
                                class="pagebuilder-mobile-only" src="{{media url=wysiwyg/Mi_proyecto_1.jpg}}" alt=""
                                title="" data-element="mobile_image" data-pb-style="WL917L3"></figure>
                    </div>
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="X6X8P03">
                        <div data-content-type="text" data-appearance="default" data-element="main"
                             data-pb-style="F4Q0BIE"><p class="MsoNormal" style="text-align: justify;">La <span
                                    style="font-size: 20px;"><strong>Tucana 9S</strong></span> es una bicicleta versátil
                                y eficiente, será la mejor compañía para senderos con diferentes tipos de terreno. Su
                                geometría ideal brinda al ciclista gran comodidad, su suspensión hidráulica Suntour XCM
                                es ideal para quienes quieran obtener una conducción bastante cómoda y fácil y su
                                sistema de cambios Shimano Alivio/Altus otorga eficiencia en una gama para uso ocasional
                                en caminos no muy complicados.</p></div>
                    </div>
                </div>
            </div>
            <div data-content-type="divider" data-appearance="default" data-element="main">
                <hr data-element="line" data-pb-style="OJLLULW">
            </div>
            <div data-content-type="video" data-appearance="default" data-element="main" data-pb-style="L33T0U4">
                <div class="pagebuilder-video-inner" data-element="inner" data-pb-style="T81C5D2">
                    <div class="pagebuilder-video-wrapper" data-element="wrapper">
                        <div class="pagebuilder-video-container">
                            <iframe frameborder="0" allowfullscreen=""
                                    src="https://www.youtube.com/embed/o4Rp2aEa7QU?autoplay=1&amp;mute=1"
                                    autoplay="true" muted="true" data-element="video"></iframe>
                        </div>
                    </div>
                </div>
            </div>
            <div data-content-type="divider" data-appearance="default" data-element="main">
                <hr data-element="line" data-pb-style="IBXJLHP">
            </div>
            <div class="pagebuilder-column-group" data-background-images="{}" data-content-type="column-group"
                 data-appearance="default" data-grid-size="12" data-element="main" data-pb-style="AP3X06Y">
                <div class="pagebuilder-column-line" data-content-type="column-line" data-element="main"
                     data-pb-style="JLXF9GK">
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="align-center"
                         data-background-images="{}" data-element="main" data-pb-style="ONT9N6R">
                        <div data-content-type="text" data-appearance="default" data-element="main"
                             data-pb-style="R7XW7DD"><p style="text-align: justify;">La <span
                                    style="font-size: 20px;"><strong>Tucana 9S</strong></span> es diseñada para pasarla
                                bien en todos tus recorridos y en senderos con diferentes tipos de terreno, su cuadro
                                ligero y duradero de aluminio Tucana Premium, con cableado completamente interno, que
                                ofrece la gran ventaja de tener garantía de por vida. Este cuadro con soldadura pulida
                                tiene una estética excepcional y te proporcionará una bicicleta con carácter único y con
                                un estilo muy distintivo.</p>
                            <p style="text-align: justify;">Con suspensión hidráulica Suntour XCM el ciclista obtiene
                                comodidad al rodar y un muy fácil manejo, además que ahorra tiempo y dinero en
                                mantenimiento ya que este tipo de suspensiones no requiere mantenimiento constante.</p>
                            <p style="text-align: justify;">Con sistema de cambios Shimano Alivio/Altus se convierte en
                                una bicicleta de alto desempeño que proporciona más maniobrabilidad para los grupos de
                                bicicletas en la gama de de uso ocasional en caminos no muy complicados.</p>
                            <p style="text-align: justify;">Con sistema de frenos Shimano de disco hidráulicos permite
                                que el ciclista viva la mejor experiencia al rodar en todo tipo de senderos y con una
                                potencia de frenado ajustada. El alcance de las manetas de este sistema esta diseñado
                                para ajustarse a la biomecánica de cualquier persona y su rendimiento de frenado fiable
                                reduce también el ruido al momento de generar la vibración de las pastillas.</p></div>
                    </div>
                </div>
            </div>
        </div>
        <div data-content-type="tab-item" data-appearance="default" data-tab-name="Características"
             data-background-images="{}" data-element="main" id="V4UDEJV" data-pb-style="QXMXQ45">
            <div data-content-type="html" data-appearance="default" data-element="main" data-pb-style="X6VXB0I">
                <style>
                    td:first-child {
                        max-width: none;
                        font-weight: bold;
                        text-align: left;
                    }

                    tr td {
                        text-align: center;
                        border-bottom: 1px solid;
                    }

                    tr:nth-child(even) {
                        background-color: #eeeded;
                    }

                    table {
                        font-size: 14px;
                    }
                </style>
                <table border="1" cellpadding="1" cellspacing="1">
                    <tbody>
                    <tr>
                        <td>MARCO</td>
                        <td>Optimus Tucana Aluminio rin 29&amp;quot;, con gu&amp;iacute;as para cableado interno de
                            frenos y cambios, compatible con mordazas de disco tipo Post Mount, u&amp;ntilde;a integrada
                            al marco. Eje de puntilla 10 X 135mm. Frente Tapered (C&amp;oacute;nico) 1 - 1/8. BSA BB
                        </td>
                    </tr>
                    <tr>
                        <td>TENEDOR</td>
                        <td>Suspensi&amp;oacute;n hidr&amp;aacute;ulica SR Suntour XCM con bloque remoto, rin 29&amp;rdquo;,
                            recorrido 100mm, eje de puntilla 9 X 100mm, bobina con ajustador de precarga, tubo de la
                            horquilla 1.1/8&amp;quot;
                        </td>
                    </tr>
                    <tr>
                        <td>PISTAS DE DIRECCI&amp;Oacute;N</td>
                        <td>Optimus Semi-integradas 1 - 1/8, Tapered type (tipo c&amp;oacute;nica), rodamiento sellado
                        </td>
                    </tr>
                    <tr>
                        <td>MANUBRIO / MANILLAR</td>
                        <td>Optimus Aluminio, 31.8 mm, 9&amp;deg;, altura de 5 mm, Longitud: 720mm (Talla S y XS)<br/>
                            Y 780 mm (Tallas M y L)
                        </td>
                    </tr>
                    <tr>
                        <td>ESPIGA/POTENCIA</td>
                        <td>Optimus Aluminio, 31.8mm, 17&amp;deg;, Longitud: 60mm (Tallas S y XS) y 80mm (Tallas M y
                            L)
                        </td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">POSTE DE SILL&amp;Iacute;N</span></span>
                        </td>
                        <td>Optimus Aluminio, 30.4mm, Longitud: 350mm (Tallas S y XS) y 400mm (Tallas M y L)&amp;nbsp;
                        </td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">MANGOS&amp;nbsp;&amp;nbsp; &amp;nbsp;</span></span>
                        </td>
                        <td>Optimus dise&amp;ntilde;o ergon&amp;oacute;mico, Longitud 125mm</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">SILL&amp;Iacute;N&amp;nbsp;&amp;nbsp; &amp;nbsp;</span></span>
                        </td>
                        <td>Optimus dise&amp;ntilde;o ergon&amp;oacute;mico, Longitud 28mm</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">PALANCAS DE CAMBIOS</span></span>
                        </td>
                        <td>Shimano Alivio SL-M3100, Rapidfire Plus 9 velocidades con Optical Gear Display</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">TENSOR&amp;nbsp;&amp;nbsp; &amp;nbsp;</span></span>
                        </td>
                        <td>Shimano Alivio RD-M3100, Shadow RD</td>
                    </tr>
                    <tr>
                        <td>DESCARRILADOR&amp;nbsp;&amp;nbsp; &amp;nbsp;</td>
                        <td>Shimano Altus FD-M2020, Top Swing, Montaje de abrazadera</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">PLATO</span></span></td>
                        <td>Biplato Shimano FC-MT210-2, 22-36T, 2x9 velocidades, Hyperdrive, con biela anodizada 170mm
                        </td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">CENTRO</span></span></td>
                        <td>Optimus BSA 68mm, 1.37x24mm</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">CASSETTE</span></span>
                        </td>
                        <td>Optimus 11-40T, 9 velocidades</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">CADENA&amp;nbsp;&amp;nbsp; &amp;nbsp;</span></span>
                        </td>
                        <td>KMC, 9 velocidades</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">FRENO</span></span></td>
                        <td>Shimano Disco Hidr&amp;aacute;ulico AMT200, Disco Center Lock, disco delantero 160mm, disco
                            trasero 160mm
                        </td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">MANZANAS</span></span>
                        </td>
                        <td>Shimano HB-TX505, Center Lock, para freno de disco con cierre r&amp;aacute;pido, 32H</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">RADIOS</span></span></td>
                        <td>Acero inoxidable 14g</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">RIN</span></span></td>
                        <td>29&amp;quot; Optimus aluminio, Doble pared, 32 huecos, ancho 18mm</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">LLANTAS/CORAZAS</span></span>
                        </td>
                        <td>Kenda 29x2.10, labrado MTB mixto</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">NEUM&amp;Aacute;TICOS</span></span>
                        </td>
                        <td>29X2.10&amp;quot; v&amp;aacute;lvula A/V</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">PEDAL</span></span></td>
                        <td>Optimus Aluminio, 9/16</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">PESO</span></span></td>
                        <td>16-17 Kg</td>
                    </tr>
                    <tr>
                        <td><span style="font-size:11.0pt"><span
                                    style="font-family:&amp;quot;Calibri&amp;quot;,sans-serif">LIMITE DE PESO</span></span>
                        </td>
                        <td>Esta bicicleta tiene un l&amp;iacute;mite de peso m&amp;aacute;ximo 130Kg (peso combinado de
                            la bicicleta, el ciclista y la carga)
                        </td>
                    </tr>
                    </tbody>
                </table>

                <p>&amp;nbsp;</p>
            </div>
        </div>
        <div data-content-type="tab-item" data-appearance="default" data-tab-name="Geometría"
             data-background-images="{}" data-element="main" id="N0LTS12" data-pb-style="N2WQJIC">
            <div class="pagebuilder-column-group" data-background-images="{}" data-content-type="column-group"
                 data-appearance="default" data-grid-size="12" data-element="main" data-pb-style="ER6X3EN">
                <div class="pagebuilder-column-line" data-content-type="column-line" data-element="main"
                     data-pb-style="HS8R1IU">
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="PVAI2HJ">
                        <div data-content-type="html" data-appearance="default" data-element="main"
                             data-pb-style="BA6HLUF">
                            <style>
                                td:first-child {
                                    max-width: none;
                                    font-weight: bold;
                                    text-align: left;
                                }

                                tr td {

                                    text-align: center;
                                    border-bottom: 1px solid;
                                }

                                tr:nth-child(even) {
                                    background-color: #eeeded;
                                }

                                table {
                                    font-size: 14px;
                                }
                            </style>
                            <table border="1" cellpadding="1" cellspacing="1">
                                <tbody>
                                <tr>
                                    <td>TABLA DE MEDIDAS</td>
                                    <td style="text-align:center">XS</td>
                                    <td style="text-align:center">S</td>
                                    <td style="text-align:center">M</td>
                                    <td style="text-align:center">L</td>
                                </tr>
                                <tr>
                                    <td>A- Longitud del tubo superior (horizontal):&amp;nbsp;</td>
                                    <td style="text-align:center">582 mm</td>
                                    <td style="text-align:center">576 mm</td>
                                    <td style="text-align:center">572 mm</td>
                                    <td style="text-align:center">573 mm</td>
                                </tr>
                                <tr>
                                    <td>B- Longitud tubo del sill&amp;iacute;n:</td>
                                    <td style="text-align:center">370 mm</td>
                                    <td style="text-align:center">406 mm</td>
                                    <td style="text-align:center">457 mm</td>
                                    <td style="text-align:center">495 mm</td>
                                </tr>
                                <tr>
                                    <td>C- Longitud tubo de direcci&amp;oacute;n:</td>
                                    <td style="text-align:center">100 mm</td>
                                    <td style="text-align:center">100 mm</td>
                                    <td style="text-align:center">100 mm</td>
                                    <td style="text-align:center">100 mm</td>
                                </tr>
                                <tr>
                                    <td>D- Angulo de la direcci&amp;oacute;n:</td>
                                    <td style="text-align:center">71&amp;deg;</td>
                                    <td style="text-align:center">71&amp;deg;</td>
                                    <td style="text-align:center">71&amp;deg;</td>
                                    <td style="text-align:center">71&amp;deg;</td>
                                </tr>
                                <tr>
                                    <td>E- Altura eje pedalier:</td>
                                    <td style="text-align:center">54.9 mm</td>
                                    <td style="text-align:center">54.9 mm</td>
                                    <td style="text-align:center">55 mm</td>
                                    <td style="text-align:center">55 mm</td>
                                </tr>
                                <tr>
                                    <td>F- Longitud de la tijera inferior:</td>
                                    <td style="text-align:center">460 mm</td>
                                    <td style="text-align:center">460 mm</td>
                                    <td style="text-align:center">460 mm</td>
                                    <td style="text-align:center">460 mm</td>
                                </tr>
                                <tr>
                                    <td>G- Angulo tubo del asiento:</td>
                                    <td style="text-align:center">73.5&amp;deg;</td>
                                    <td style="text-align:center">73.5&amp;deg;</td>
                                    <td style="text-align:center">73.5&amp;deg;</td>
                                    <td style="text-align:center">73.5&amp;deg;</td>
                                </tr>
                                <tr>
                                    <td>H- Distancia entre ejes:</td>
                                    <td style="text-align:center">111 mm</td>
                                    <td style="text-align:center">111.5 mm</td>
                                    <td style="text-align:center">112.5&amp;nbsp;mm</td>
                                    <td style="text-align:center">113.5&amp;nbsp;mm</td>
                                </tr>
                                <tr>
                                    <td>I- Altura del pedalier:</td>
                                    <td style="text-align:center">310 mm</td>
                                    <td style="text-align:center">310 mm</td>
                                    <td style="text-align:center">310 mm</td>
                                    <td style="text-align:center">310 mm</td>
                                </tr>
                                <tr>
                                    <td>J- Alcance del cuadro:</td>
                                    <td style="text-align:center">480 mm</td>
                                    <td style="text-align:center">490&amp;nbsp;mm</td>
                                    <td style="text-align:center">500 mm</td>
                                    <td style="text-align:center">510 mm</td>
                                </tr>
                                <tr>
                                    <td>K- Altura del cuadro:</td>
                                    <td style="text-align:center">590 mm</td>
                                    <td style="text-align:center">600 mm</td>
                                    <td style="text-align:center">610 mm</td>
                                    <td style="text-align:center">630 mm</td>
                                </tr>
                                <tr>
                                    <td>L- Standover:</td>
                                    <td style="text-align:center">710 mm</td>
                                    <td style="text-align:center">720 mm</td>
                                    <td style="text-align:center">740 mm</td>
                                    <td style="text-align:center">780 mm</td>
                                </tr>
                                <tr>
                                    <td>M- Longitud de la tijera superior:</td>
                                    <td style="text-align:center">441 mm</td>
                                    <td style="text-align:center">455&amp;nbsp;mm</td>
                                    <td style="text-align:center">476&amp;nbsp;mm</td>
                                    <td style="text-align:center">494 mm</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="WSOXO02">
                        <figure data-content-type="image" data-appearance="full-width" data-element="main"
                                data-pb-style="INV3X4E"><img class="pagebuilder-mobile-hidden"
                                                             src="{{media url=wysiwyg/Tucana-medidas_1__1.jpg}}" alt=""
                                                             title="" data-element="desktop_image"
                                                             data-pb-style="WSB8P4T"><img
                                class="pagebuilder-mobile-only" src="{{media url=wysiwyg/Tucana-medidas_1__1.jpg}}"
                                alt="" title="" data-element="mobile_image" data-pb-style="RM0OS9O"></figure>
                    </div>
                </div>
            </div>
        </div>
        <div data-content-type="tab-item" data-appearance="default" data-tab-name="Tecnología"
             data-background-images="{}" data-element="main" id="LBBTNDB" data-pb-style="GULP6O5">
            <div class="pagebuilder-column-group" data-background-images="{}" data-content-type="column-group"
                 data-appearance="default" data-grid-size="12" data-element="main" data-pb-style="WLT33Y4">
                <div class="pagebuilder-column-line" data-content-type="column-line" data-element="main"
                     data-pb-style="B3QEBME">
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="VK3YGGS">
                        <div data-content-type="text" data-appearance="default" data-element="main"><p
                                style="text-align: center;">Cuadro aluminio Tucana Premium que le otorga a la bicicleta
                                ligereza y durabilidad, con una geometría de trail que inspira confianza para todos tus
                                recorridos, con guiado completamente interno y soldadura pulida en las uniones del
                                frente y de la barra del sillín del cuadro para un diseño más sofisticado. Obtendrás una
                                bicicleta única y con un estilo muy distintivo.</p></div>
                    </div>
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="GOHNECL">
                        <figure data-content-type="image" data-appearance="full-width" data-element="main"
                                data-pb-style="PCRT4IQ"><img class="pagebuilder-mobile-hidden"
                                                             src="{{media url=wysiwyg/Captura_1.JPG}}" alt="" title=""
                                                             data-element="desktop_image" data-pb-style="N9VID07"><img
                                class="pagebuilder-mobile-only" src="{{media url=wysiwyg/Captura_1.JPG}}" alt=""
                                title="" data-element="mobile_image" data-pb-style="NK5LJDS"></figure>
                    </div>
                </div>
                <div class="pagebuilder-column-line" data-content-type="column-line" data-element="main"
                     data-pb-style="C55NTUS">
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="OMDHBBM">
                        <figure data-content-type="image" data-appearance="full-width" data-element="main"
                                data-pb-style="UOR7JI1"><img class="pagebuilder-mobile-hidden"
                                                             src="{{media url=wysiwyg/Sin_t_tulo_1.jpg}}" alt=""
                                                             title="" data-element="desktop_image"
                                                             data-pb-style="JN4N1US"><img
                                class="pagebuilder-mobile-only" src="{{media url=wysiwyg/Sin_t_tulo_1.jpg}}" alt=""
                                title="" data-element="mobile_image" data-pb-style="NE03FKD"></figure>
                    </div>
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="QGE098C">
                        <div data-content-type="text" data-appearance="default" data-element="main"><p id="UVSQX45"
                                                                                                       style="text-align: center;">
                                Suspensión hidraúlica Suntour XCM que brinda comodidad y fácil manejo lo que se traduce
                                en una bicicleta adaptable en cualquier tipo de terreno y con la gran ventanja del
                                bloqueo remoto que evita la pérdida de fuerza de pedaleo cuando no es necesaria la
                                amortiguación.</p></div>
                    </div>
                </div>
                <div class="pagebuilder-column-line" data-content-type="column-line" data-element="main"
                     data-pb-style="K4CAPRK">
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="LPNAY8B">
                        <div data-content-type="text" data-appearance="default" data-element="main"
                             data-pb-style="LB22LBT"><p>Sistema de frenos de disco hidráulicos Shimano AMT200 que ofrece
                                al ciclista alta potencia de frenado con dosificación precisa, con un alcance de las
                                manetas diseñado para ajustarse a la biomecánica de cualquier persona y con un
                                rendimiento de frenado fiable que también disminuye significativamente el ruido al
                                momento de generar la vibración de las pastillas.</p>
                            <p>&nbsp;</p>
                            <p>&nbsp;</p></div>
                    </div>
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="V3SC9AA">
                        <figure data-content-type="image" data-appearance="full-width" data-element="main"
                                data-pb-style="KRXUTYJ"><img class="pagebuilder-mobile-hidden"
                                                             src="{{media url=wysiwyg/Mi_proyecto_1_.png}}" alt=""
                                                             title="" data-element="desktop_image"
                                                             data-pb-style="KX5R3MI"><img
                                class="pagebuilder-mobile-only" src="{{media url=wysiwyg/Mi_proyecto_1_.png}}" alt=""
                                title="" data-element="mobile_image" data-pb-style="IV2SJ6L"></figure>
                    </div>
                </div>
                <div class="pagebuilder-column-line" data-content-type="column-line" data-element="main"
                     data-pb-style="KNXPWY5">
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="TTTXLJ5">
                        <figure data-content-type="image" data-appearance="full-width" data-element="main"
                                data-pb-style="XJI0UVI"><img class="pagebuilder-mobile-hidden"
                                                             src="{{media url=wysiwyg/Sin_t_tulo_2.jpg}}" alt=""
                                                             title="" data-element="desktop_image"
                                                             data-pb-style="NW69DC4"><img
                                class="pagebuilder-mobile-only" src="{{media url=wysiwyg/Sin_t_tulo_2.jpg}}" alt=""
                                title="" data-element="mobile_image" data-pb-style="IQ61NPS"></figure>
                    </div>
                    <div class="pagebuilder-column" data-content-type="column" data-appearance="full-height"
                         data-background-images="{}" data-element="main" data-pb-style="VQGL9C1">
                        <div data-content-type="text" data-appearance="default" data-element="main"
                             data-pb-style="S6YPJJJ"><p>Sistema CENTER LOCK el cual permite una fácil instalación del
                                disco con montaje de ranura y un anillo de cierre, reduce las horas de trabajo
                                disminuyendo el tiempo tanto de instalación como de desmontaje. Como plus adicional, la
                                fijación de seguridad con el montaje de ranura aumenta la precisión y la rigidez y esto
                                mejora la eficiencia del frenado.</p></div>
                    </div>
                </div>
            </div>
        </div>
        <div data-content-type="tab-item" data-appearance="default" data-tab-name="Beneficios"
             data-background-images="{}" data-element="main" id="GYI8697" data-pb-style="DVWU7QI">
            <figure data-content-type="image" data-appearance="full-width" data-element="main" data-pb-style="YPTGKLL">
                <img class="pagebuilder-mobile-hidden" src="{{media url=wysiwyg/Life_time.JPG}}" alt="" title=""
                     data-element="desktop_image" data-pb-style="DWHSGDW"><img class="pagebuilder-mobile-only"
                                                                               src="{{media url=wysiwyg/Life_time.JPG}}"
                                                                               alt="" title=""
                                                                               data-element="mobile_image"
                                                                               data-pb-style="TAAIMMI"></figure>
            <div data-content-type="text" data-appearance="default" data-element="main"><p style="text-align: center;">
                    <span style="font-size: 20px;">Para activar la garantía extendida limitada, es necesario que el distribuidor autorizado realice el registro en nuestra plataforma <a
                            tabindex="0" href="https://www.optimusbikes.com/" target="_blank" rel="noopener"><span
                                style="color: #236fa1;"><strong>OptimusBikes</strong></span></a></span></p>
                <p style="text-align: center;"><span style="font-size: 20px;">Para más información, <a tabindex="0"
                                                                                                       href="https://www.optimusbikes.com/pages/garantia-extendida"
                                                                                                       target="_blank"
                                                                                                       rel="noopener"><span
                                style="color: #236fa1;"><strong>ingresa aquí.</strong></span></a></span></p></div>
            <figure data-content-type="image" data-appearance="full-width" data-element="main" data-pb-style="G4JPTI2">
                <img class="pagebuilder-mobile-hidden" src="{{media url=wysiwyg/new_frame.JPG}}" alt="" title=""
                     data-element="desktop_image" data-pb-style="FW2HFS0"><img class="pagebuilder-mobile-only"
                                                                               src="{{media url=wysiwyg/new_frame.JPG}}"
                                                                               alt="" title=""
                                                                               data-element="mobile_image"
                                                                               data-pb-style="YVFKH41"></figure>
            <div data-content-type="text" data-appearance="default" data-element="main"><p style="text-align: center;">
                    <span style="font-size: 20px;">Para más información, <a tabindex="0"
                                                                            href="https://www.optimusbikes.com/pages/frame-pact"><span
                                style="color: #236fa1;"><strong>ingresa aquí.</strong></span></a></span></p></div>
            <figure data-content-type="image" data-appearance="full-width" data-element="main" data-pb-style="YQ817RO">
                <img class="pagebuilder-mobile-hidden" src="{{media url=wysiwyg/Bike_pact.JPG}}" alt="" title=""
                     data-element="desktop_image" data-pb-style="QBPTBQN"><img class="pagebuilder-mobile-only"
                                                                               src="{{media url=wysiwyg/Bike_pact.JPG}}"
                                                                               alt="" title=""
                                                                               data-element="mobile_image"
                                                                               data-pb-style="V3IWSCQ"></figure>
            <div data-content-type="text" data-appearance="default" data-element="main"><p id="BNLPDNO"
                                                                                           style="text-align: center;">
                    <span style="font-size: 20px;">Para más información, <a tabindex="0"
                                                                            href="https://www.optimusbikes.com/pages/pacto-de-reposicion-1"><span
                                style="color: #236fa1;"><strong>ingresa aquí.</strong></span></a></span></p></div>
        </div>
        <div data-content-type="tab-item" data-appearance="default" data-tab-name="Documentos"
             data-background-images="{}" data-element="main" id="NRDV67W" data-pb-style="R0N8R2A">
            <div data-content-type="html" data-appearance="default" data-element="main" data-pb-style="MMV54CO">
                <embed src="https://bicicletasmilan.com/MANUAL%20OPTIMUS%202022.pdf" type="application/pdf" width="90%"
                       height="1080px"/>
            </div>
        </div>
    </div>
</div>
