<?php
/** @var \Wagento\Catalog\Block\MessageVerifyStock $block */
?>
<div id="message-verify-stock" data-bind="scope: 'message-verify-stock'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "#message-verify-stock": {
            "Magento_Ui/js/core/app": {
                "components":{
                    "message-verify-stock": {
                        "component":"Wagento_Catalog\/js\/view\/message-verify-stock"
                    }
                }
            }
        }
    }
</script>
