<?php
/**
 * Rutavity configurable product price template
 * @package Milan_Rutavity
 * @author Rudie Wang <rudi.wang@wagento.com>
 */

/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$blockHtml = '';
?>

<?php if (!$block->isProductList() && $block->hasSpecialPrice()) : ?>
    <?php $blockHtml .= '<span class="old-price sly-old-price no-display">';?>
    <?php $blockHtml .= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
        'display_label'     => __('Regular Price'),
        'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
        'price_type'        => 'oldPrice',
        'include_container' => true,
        'skip_adjustments'  => true
    ]); ?>
    <?php $blockHtml .= '</span>';?>
<?php endif; ?>

<?php $blockHtml .= '<span class="normal-price">';?>
<?php $blockHtml .= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
    'display_label' => __('As low as'),
    'price_id' => $block->getPriceId('product-price-' . $idSuffix),
    'price_type' => 'finalPrice',
    'include_container' => true,
    'schema' => $schema,
]);
?>
<?php $blockHtml .= '</span>';?>

<?php if ($block->showMinimalPrice()) : ?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        <?php $blockHtml .= '<a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">';?>
        <?php $blockHtml .= /* @noEscape */ $block->renderAmountMinimal();?>
        <?php $blockHtml .= '</a>';?>
    <?php else :?>
        <?php $blockHtml .= '<span class="minimal-price-link">';?>
        <?php $blockHtml .= /* @noEscape */ $block->renderAmountMinimal();?>
        <?php $blockHtml .= '</span>';?>
    <?php endif?>
<?php endif; ?>
<?php if ($block->getRequest()->isAjax()):?>
    <?php echo $blockHtml;?>
<?php else:?>
    <div id="<?= $block->getPriceId('show-price-without-login-' . $idSuffix) ?>" data-bind="scope: '<?= $block->getPriceId('show-price-without-login-' . $idSuffix) ?>'">
        <div data-bind="html: getBlockHtml()"></div>
    </div>
    <script type="text/x-magento-init">
        {
            "#<?= $block->getPriceId('show-price-without-login-' . $idSuffix) ?>": {
                "Magento_Ui/js/core/app": {
                    "components":{
                        "<?= $block->getPriceId('show-price-without-login-' . $idSuffix) ?>": {
                            "component":"Wagento_Catalog\/js\/view\/show-price-without-login",
                            "blockPrice": "<?=str_replace("\n", "", str_replace("\"", "\\\"", $blockHtml));?>"
                        }
                    }
                }
            }
        }
    </script>
<?php endif;?>
