<?php
/**
 * Copyright © Wagento, Inc. All rights reserved.
 */
/** @var \Wagento\Sales\Block\Order\History\Orders $block */
?>
<?php $orders = $block->getOrders(); ?>
<?php foreach ($orders as $order) : ?>
    <div class="row">
        <div class="order_data">
            <div class="date">
                <span><?=__('Placed Order');?></span>
                <span><?=$block->formatDate($order->getCreatedAt(), \IntlDateFormatter::LONG);?></span>
            </div>
            <div class="total">
                <span><?=__('Total');?></span>
                <span><?= /* @noEscape */ $order->formatPrice($order->getGrandTotal()) ?></span>
            </div>
            <div class="number-actions">
                <span><?=__('Order #');?><?=$block->escapeHtml($order->getRealOrderId());?></span>
                <div class="actions">
                    <a href="<?= $block->escapeUrl($block->getViewUrl($order)) ?>" class="action view">
                        <span><?= $block->escapeHtml(__('Order Details')) ?></span>
                    </a>

                    <?php if ($order->hasInvoices()):?>
                        <a href="<?= $block->escapeUrl($block->getInvoiceUrl($order)) ?>" class="action view">
                            <span> | <?= $block->escapeHtml(__('Invoice')) ?></span>
                        </a>
                    <?php endif ?>

                    <?php if ($order->hasCreditmemos()):?>
                        <a href="<?= $block->escapeUrl($block->getCreditMemoUrl($order)) ?>" class="action view">
                            <span> | <?= $block->escapeHtml(__('Creditmemo')) ?></span>
                        </a>
                    <?php endif ?>
                </div>
            </div>
        </div>
        <?php if ($block->getShowItems()) :?>
            <div class="order_items">
                <?php /** @var \Magento\Sales\Model\Order\Item $item */ ?>
                <?php foreach ($order->getAllItems() as $item): ?>
                    <?php if($item->getProduct()) {continue;} ?>
                    <?php if ($item->getHasChildren()) {continue;}?>
                    <div class="row">
                        <div class="image">
                            <?=$block->getImage($item->getProduct(), 'cart_page_product_thumbnail')->toHtml();?>
                        </div>
                        <div class="data" >
                            <div>
                                <span class="name"><?=$item->getName();?></span>
                                <?php
                                if ($options = $block->getItemOptions($item)) {
                                    foreach ($options as $option) {
                                        echo "<span class='options options_label'>{$option['label']}: </span>";
                                        echo "<span class='options options_value'>{$option['value']}</span>";
                                    }
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif;?>
    </div>
<?php endforeach; ?>
