<?php
/**
 * Rutavity header top bar mini-logo template
 * @package Milan_Rutavity
 * @author Rudie Wang <rudi.wang@wagento.com>
 */

/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 */
$path = $block->getLogoFile();
$label = $block->getLogoAlt();
?>
<a class="mini-logos" href="<?=$block->getUrl('catalog/category/view/category/optimus/');?>">
    <img src="<?= $block->escapeHtml($block->getViewFileUrl('images/assets/optimus.svg')) ?>" alt="<?= $block->escapeHtml($label) ?>" />
</a>
<a class="mini-logos" href="<?=$block->getUrl('catalog/category/view/category/profit/');?>">
    <img src="<?= $block->escapeHtml($block->getViewFileUrl('images/assets/profit.svg')) ?>" alt="<?= $block->escapeHtml($label) ?>" />
</a>
<a class="mini-logos" href="<?=$block->getUrl('catalog/category/view/category/orbea/');?>">
    <img src="<?= $block->escapeHtml($block->getViewFileUrl('images/assets/orbea.svg')) ?>" alt="<?= $block->escapeHtml($label) ?>" />
</a>
