<?php
/**
 * Rutavity customer account authorization template
 * @package Milan_Rutavity
 * @author Rudie Wang <rudi.wang@wagento.com>
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams()); ?>
    <li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('|')) ?>">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
            <?= /* @noEscape */ $dataPostParam ?>>
            <i class="rt-icon rt-icon-login"></i>
        </a>
    </li>
<?php } else { ?>
    <li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('|')) ?>">
        <a id="do-login">
            <i class="rt-icon rt-icon-login"></i>
        </a>
        <?php echo $block->getBlockHtml('login-popup');?>
        <?php echo $block->getBlockHtml('customer_form_popup');?>
    </li>
<?php } ?>
