<?php
/**
 * Rutavity customer account authorization template
 * @package Milan_Rutavity
 * @author Rudie Wang <rudi.wang@wagento.com>
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams()); ?>
    <li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('|')) ?>">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
            <?= /* @noEscape */ $dataPostParam ?>>
            <i class="rt-icon rt-icon-logout"></i>
            <span class="text-logout"><?=__('Logout');?></span>
        </a>
    </li>
<?php } else { ?>
    <li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('|')) ?>">
        <a id="do-login">
            <?php echo $block->getBlockHtml('login-popup');?>
            <?php echo $block->getBlockHtml('customer_form_popup');?>
            <i class="rt-icon rt-icon-login"></i>
            <span><?=__('Sign In');?></span>
        </a>

    </li>
<?php } ?>
