<?php
/**
 * Copyright © Wagento, Inc. All rights reserved.
 */

use Magento\Framework\View\Helper\SecureHtmlRenderer;

/**
 * Create account form template
 *
 * @var Magento\Framework\View\Element\Template $block
 * @var SecureHtmlRenderer $secureRenderer
 */
?>

<div class="form-create-account-popup"
     id="form-create-company-account-popup"
     style="display: none;">
    <?php echo $block->getBlockHtml('wagento_company_account_create');?>
</div>
