# The services of the project.
#
# Each service listed will be deployed to power your project.

mysql:
    type: mysql:10.6
    disk: 3062

redis:
    type: redis:7.0

elasticsearch:
    type: elasticsearch:7.7
    disk: 1024

rabbitmq:
  type: rabbitmq:3.9
  disk: 1024
