<?php
/**
 * Rutavity checkout success page invoice form
 * @package Milan_Rutavity
 * @author Rudie Wang <rudi.wang@wagento.com>
 */

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="success-invoice-form">
    <form class="form form-invoice">
        <fieldset class="fieldset invoice" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
            <div class="actions-toolbar">
                <a class="action secondary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>">
                    <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
                </a>
            </div>
        </fieldset>
    </form>
</div>
