<?php
/**
 * Rutavity checkout success page order items
 * @package Milan_Rutavity
 * @author Rudie Wang <rudi.wang@wagento.com>
 */

?>
<?php
/** @var $block \Magento\Checkout\Block\Onepage\Success */

$orderItems = $block->getPurchaseOrder()->getSnapshotQuote()->getAllItems() ?? [];
?>
<div class="success-order-items">
    <div class="items">
        <?php foreach ($orderItems ?? [] as $orderItem): ?>
            <?php
            /** @var $orderItem \Magento\Sales\Model\Order\Item */
            if ($orderItem->getParentItem()) {
                continue;
            }
            ?>
        <table class="item">
            <thead>
            <tr>
                <th colspan="4"><?= $block->escapeHtml(__('Order Articles')) ?></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td colspan="4"><?= $orderItem->getName() ?></td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
                <th><?= $block->escapeHtml(__('Qty')) ?></th>
                <td><?= round($orderItem->getQty(), 0) ?></td>
                <th><?= $block->escapeHtml(__('Price')) ?></th>
                <td><?= $block->getFormattedPrice($orderItem->getPrice()) ?></td>
            </tr>
            </tfoot>
        </table>
        <?php endforeach;; ?>
    </div>
    <table class="total">
        <tbody>
        <tr>
            <td class="total-label"><?= $block->escapeHtml(__('Subtotal')) ?></td>
            <td class="total-value"><?= $block->getSubtotal() ?></td>
        </tr>
        <tr>
            <td class="total-label"><?= $block->escapeHtml(__('Shipping Amount')) ?></td>
            <td class="total-value"><?= $block->getShippingAmount() ?></td>
        </tr>
        <?php if ($block->getDiscountAmount()): ?>
            <tr>
                <td class="total-label"><?= $block->escapeHtml(__('Discount Amount')) ?></td>
                <td class="total-value"><?= $block->getDiscountAmount() ?></td>
            </tr>
        <?php endif; ?>
        <tr>
            <td class="total-label"><?= $block->escapeHtml(__('Grand Total')) ?></td>
            <td class="total-value"><?= $block->getGrandTotal() ?></td>
        </tr>
        </tbody>
    </table>
</div>
