<?php
/** @var \Wagento\ImportData\Block\Product\Characteristic $block */
?>
<table border="1" cellpadding="1" cellspacing="1">
    <tbody>
        <?php foreach ($block->getAttributeCodeAllowedToShow() as $attribute):?>
            <?php if (!$block->getCustomAttributesValue($attribute)) {continue;}?>
            <tr>
                <td><?=$block->getCustomAttributesLabel($attribute);?></td>
                <td><?=$block->getCustomAttributesValue($attribute);?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
