<?php
/** @var \Wagento\ImportData\Block\Product\Documents $block */
?>
<div data-content-type="text"
     data-appearance="default"
     data-element="main"
     data-pb-style="F4Q0BIE">
    <?=__('Save the manual');?>
    <a href="<?=$block->getUrlFile();?>" download><?=__('click here.');?></a>
</div>
<iframe src="https://drive.google.com/viewerng/viewer?embedded=true&url=<?=$block->getUrlFile();?>"
        type="application/pdf"
        width="90%"
        height="680px"/>
