<?php
/**
 * Rutavity review list template
 * @package Milan_Rutavity
 * @author Rudie Wang <rudi.wang@wagento.com>
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Review\Block\Product\View\ListView;

/**
 * @var ListView $block
 * @var SecureHtmlRenderer $secureRenderer
 * @var Escaper $escaper
 */

$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)): ?>
    <div class="block review-list" id="customer-reviews">
        <div class="block-content">
            <div class="toolbar review-toolbar">
                <?= $block->getChildHtml('toolbar') ?>
            </div>
            <ol class="items review-items">
                <?php foreach ($_items as $_review): ?>
                    <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                        <?php if ($cnt = count($_review->getRatingVotes())): ?>
                            <div class="review-ratings">
                                <?php
                                $totalVotePercent = 0;
                                foreach ($_review->getRatingVotes() as $_vote):
                                    $totalVotePercent += $_vote->getPercent();
                                    ?>

                                    <div class="rating-summary item"
                                         itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                        <span class="label rating-label">
                                            <span><?= $escaper->escapeHtml($_vote->getRatingCode()) ?></span>
                                        </span>
                                        <div class="rating-result"
                                             id="review_<?= /* @noEscape */ $_review->getReviewId()
                                             . '_vote_'
                                             . $_vote->getVoteId() ?>"
                                             title="<?= $escaper->escapeHtmlAttr($_vote->getPercent()) ?>%">
                                            <meta itemprop="worstRating" content="1"/>
                                            <meta itemprop="bestRating" content="100"/>
                                            <span>
                                                <span itemprop="ratingValue">
                                                    <?= $escaper->escapeHtml($_vote->getPercent()) ?>%
                                                </span>
                                            </span>
                                        </div>
                                        <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                            'width:' . $_vote->getPercent() . '%',
                                            'div#review_' . $_review->getReviewId()
                                            . '_vote_' . $_vote->getVoteId() . ' span'
                                        ) ?>
                                    </div>
                                <?php endforeach; ?>
                                <?php $avgPercent = $totalVotePercent / $cnt; ?>
                                <div class="rating-summary rating-summary-avg item"
                                     itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                    <div class="rating-result"
                                         id="review_<?= /* @noEscape */ $_review->getReviewId() ?>"
                                         title="<?= $escaper->escapeHtmlAttr($avgPercent) ?>%">
                                        <meta itemprop="worstRating" content="1"/>
                                        <meta itemprop="bestRating" content="100"/>
                                        <span>
                                            <span itemprop="ratingValue">
                                                <?= $escaper->escapeHtml($avgPercent) ?>%
                                            </span>
                                        </span>
                                    </div>
                                    <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        'width:' . $_vote->getPercent() . '%',
                                        'div#review_' . $_review->getReviewId() . ' span'
                                    ) ?>
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="review-details">
                            <p class="review-author">
                                <span class="review-details-label">
                                    <?= $escaper->escapeHtml(__('Review by')) ?>
                                </span>
                                <strong class="review-details-value" itemprop="author">
                                    <?= $escaper->escapeHtml($_review->getNickname()) ?>
                                </strong>
                            </p>
                            <p class="review-date">
                                <span class="review-details-label">
                                    <?= $escaper->escapeHtml(__('Posted on')) ?>
                                </span>
                                <time class="review-details-value" itemprop="datePublished"
                                      datetime="<?= $escaper->escapeHtmlAttr($block->formatDate(
                                          $_review->getCreatedAt(),
                                          $format
                                      )) ?>">
                                    <?= $escaper->escapeHtml(
                                        $block->formatDate(
                                            $_review->getCreatedAt(),
                                            $format
                                        )
                                    ) ?>
                                </time>
                            </p>
                        </div>
                        <div class="review-title" itemprop="name">
                            <?= $escaper->escapeHtml($_review->getTitle()) ?>
                        </div>
                        <div class="review-content-container">
                            <div class="review-content" itemprop="description">
                                <?= /* @noEscape */ nl2br($escaper->escapeHtml($_review->getDetail())) ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="toolbar review-toolbar">
                <?= $block->getChildHtml('toolbar') ?>
            </div>
        </div>
    </div>
<?php endif; ?>
