<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?php
$lazyLoadHelper = $this->helper('WeltPixel\LazyLoading\Helper\Data');
$isRequestAjax = $lazyLoadHelper->isRequestAjax();
$lazyLodImgSrc = $lazyLoadHelper->getImageLoader();
$lazyLoadImgDataOriginal = $block->getImageUrl();
if ($isRequestAjax) {
    $lazyLodImgSrc = $lazyLoadImgDataOriginal;
}
?>

<?php
$lazyLoadClass = '';
if ($block->getLazyLoad()) {
    $lazyLoadClass = 'owl-lazy';
} elseif ($lazyLoadHelper->isEnabled() && !$block->getOwlcarousel()) {
    $lazyLoadClass = 'lazy';
}
?>

<span class="product-image-container product-image-container-<?= /* @noEscape */ $block->getProductId() ?>"
      style="width:<?php /* @escapeNotVerified */ echo $block->getWidth()?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?php /* @escapeNotVerified */ echo ($block->getRatio() * 100); ?>%;">
        <img class="product-image-photo <?php echo $lazyLoadClass; ?>"
            <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
                <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtmlAttr($value) ?>"
            <?php endforeach; ?>
            <?php if (!$block->getLazyLoad()): ?>
                <?php if ($lazyLoadHelper->isEnabled()  && !$block->getOwlcarousel() ) : ?>
                    src="<?php /* @escapeNotVerified */ echo $lazyLodImgSrc; ?>"
                    data-original="<?php /* @escapeNotVerified */ echo $lazyLoadImgDataOriginal; ?>"
                <?php else:  ?>
                    src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
                <?php endif; ?>
            <?php endif ;?>
            <?php if ($block->getHoverImageUrl()) :  ?>
                data-hoversrc="<?php /* @escapeNotVerified */ echo $block->getHoverImageUrl(); ?>"
                onmouseover="this.setAttribute('data-tmp', this.src);this.src=this.getAttribute('data-hoversrc');"
                onmouseout="this.src=this.getAttribute('data-tmp')"
                onmousemove="if (this.getAttribute('data-hoversrc') != this.src) this.setAttribute('data-tmp', this.src)"
            <?php endif; ?>
             width="<?php /* @escapeNotVerified */ echo $block->getWidth(); ?>"
             height="<?php /* @escapeNotVerified */ echo $block->getHeight(); ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->stripTags($block->getLabel(), null, true); ?>"
             loading="lazy"
            <?php if ($block->getLazyLoad()): ?>
                data-src="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
                data-src-retina="<?php /* @escapeNotVerified */ echo $block->getImageUrl(); ?>"
            <?php endif; ?>
        /></span>
</span>
